### ISSUE TITLE
Custom nginx conf file not applied

### ISSUE THREAD

**Issue by littlebacklash** [jkaninda/nginx-php-fpm#18]
Hi!! I'm building an image from base since I need to install some other libraries using a dockerfile. The thing is that even though a custom nginx.conf file is provided and copied to the indicated path (/var/www/html/conf/nginx/nginx.conf or /var/www/html/conf/nginx/nginx-site.conf) and build image process is succesfull, then when running the docker container, the legends "nginx-site.conf not found", "Start nginx with default config..."  are displayed.
Any piece of advice will be appreciated, since I need to provide specific directives to set headers to get real IP client address

**Comment by jkaninda** [comment]
From base, you can put the config file in /etc/nginx/nginx.conf,
/var/www/html/conf/nginx/nginx.conf is only when you run with docker-compose and want to customize the nginx config easily.
