### ISSUE TITLE
nginx custom config not working in 7.2

### ISSUE THREAD

**Issue by tidypol** [jkaninda/nginx-php-fpm#27]
https://github.com/jkaninda/nginx-php-fpm?tab=readme-ov-file#nginx-custom-config

not working for 7.2

**Comment by tidypol** [comment]
ok after inspecting the source code 2 weeks ago someone changed the behaviour dropping the cool feature of having a custom nginx config

https://github.com/jkaninda/nginx-php-fpm/blob/d024a178b89cd5efd36dc2295e0ba8baa9c10683/src/entrypoint.sh

why?

**Comment by jkaninda** [comment]
I saw it, let me restore it

**Comment by jkaninda** [comment]
Restored
